### ISSUE TITLE
Prepare v0 release (deadline: 26/05/2022)

### ISSUE THREAD

**Issue by krshrimali** [Lightning-AI/LAI-Flashy-App#44]
This issue tracks the v0 release of the Lightning Auto ML app :zap:

## Installation

Fixing issues with installation/setup:

* [x] Remove `fiftyone` from the `requirements.txt` file. (#45)
* [x] Add the caveat of installing `fiftyone` manually (locally) to README. (#45)
* [x] Raise error when `fiftyone` not installed. (#45)
* [x] Create `requirements-dev.txt` (#45)
* [x] Pin all versions in the requirements file (#45)

## Cloud

Fixing issues with making the app work on the cloud:

* [x] Make the app reusable. (#42)
* [x] Check if the app works for the Image Classification demo on the cloud.
* [x] Check if the app works for the Text Classification demo on the cloud.

## Miscellaneous

* [x] Ensure it works smoothly on the master branch. (#43)
* [x] Fix issues with protobuf (https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates). (#43)
